tasks:
  - name: SvelteKit dev server
    init: |
      cp .env.example .env
      npm install
      npm run check
      gp sync-done install
      npm run prepare
    command: npm run dev
  - name: Unit tests
    command: |
      gp sync-await install
      npm run test:unit
  - name: End to end tests
    command: |
      gp sync-await install
      npx playwright install
      npm run test

image:
  file: .gitpod.Dockerfile

ports:
  - name: SvelteKit dev server
    port: 5173
    onOpen: open-browser
    visibility: private

vscode:
  extensions:
    - svelte.svelte-vscode
    - ms-playwright.playwright
