tasks:
  - init: |
      echo -e $ENV_FILE > .env
      npm install
    command: npm start

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - mikestead.dotenv

ports:
  - name: webpack dev server
    port: 8080
    onOpen: open-browser
